/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Sparqling WS
 * This server will expose an API to Sparqling front end to create new SPARQL queries with a combinations of point and click on the [GRAPHOLscape](https://github.com/obdasystems/grapholscape) graph.  Sparqling will be released as a standalone appication but also the server will embedded in [MWS](https://github.com/obdasystems/mws) and Sparqling will be integrated in [Monolith](https://www.monolith.obdasystems.com/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GraphElement
 */
export interface GraphElement {
    /**
     * This id corrensopond to the variable when entity type is a class.
     * @type {string}
     * @memberof GraphElement
     */
    id?: any;
    /**
     * This element could refer to one variable (if it's a class) or to two variables (if it's a property)
     * @type {Array&lt;string&gt;}
     * @memberof GraphElement
     */
    variables?: any;
    /**
     * It could have more than one entity only when entity type is a class (could be derived after clicking on two borther classes)
     * @type {Array&lt;Entity&gt;}
     * @memberof GraphElement
     */
    entities?: any;
    /**
     * 
     * @type {Array&lt;GraphElement&gt;}
     * @memberof GraphElement
     */
    children?: any;
}
