/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Sparqling WS
 * This server will expose an API to Sparqling front end to create new SPARQL queries with a combinations of point and click on the [GRAPHOLscape](https://github.com/obdasystems/grapholscape) graph.  Sparqling will be released as a standalone appication but also the server will embedded in [MWS](https://github.com/obdasystems/mws) and Sparqling will be integrated in [Monolith](https://www.monolith.obdasystems.com/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface QueryGraph
 */
export interface QueryGraph {
    /**
     * 
     * @type {boolean}
     * @memberof QueryGraph
     */
    distinct?: any;
    /**
     * 
     * @type {Array&lt;HeadElement&gt;}
     * @memberof QueryGraph
     */
    head: any;
    /**
     * 
     * @type {GraphElement}
     * @memberof QueryGraph
     */
    graph: any;
    /**
     * 
     * @type {Array&lt;Filter&gt;}
     * @memberof QueryGraph
     */
    filters?: any;
    /**
     * 
     * @type {Array&lt;Optional&gt;}
     * @memberof QueryGraph
     */
    optionals?: any;
    /**
     * 
     * @type {GraphElement}
     * @memberof QueryGraph
     */
    minus?: any;
    /**
     * 
     * @type {OrderByElement}
     * @memberof QueryGraph
     */
    orderBy?: any;
    /**
     * 
     * @type {GroupByElement}
     * @memberof QueryGraph
     */
    groupBy?: any;
    /**
     * 
     * @type {Array&lt;Filter&gt;}
     * @memberof QueryGraph
     */
    having?: any;
    /**
     * 
     * @type {number}
     * @memberof QueryGraph
     */
    limit?: any;
    /**
     * 
     * @type {number}
     * @memberof QueryGraph
     */
    offset?: any;
    /**
     * 
     * @type {string}
     * @memberof QueryGraph
     */
    sparql: any;
}
