/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Sparqling WS
 * This server will expose an API to Sparqling front end to create new SPARQL queries with a combinations of point and click on the [GRAPHOLscape](https://github.com/obdasystems/grapholscape) graph.  Sparqling will be released as a standalone appication but also the server will embedded in [MWS](https://github.com/obdasystems/mws) and Sparqling will be integrated in [Monolith](https://www.monolith.obdasystems.com/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { QueryGraph } from '../models';
/**
 * QueryGraphApi - axios parameter creator
 * @export
 */
export const QueryGraphApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Explicitley add a term to the query head. All the data property variables are added automatically to the head during the query graph construction. This will add to the head only variables associated to classes (`rdf:type` triple pattern) or data properties.
         * @summary Add the head term to the query graph.
         * @param {QueryGraph} body 
         * @param {string} graphElementId The id of the graph node that should be added to the head
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addHeadTerm: async (body: QueryGraph, graphElementId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling addHeadTerm.');
            }
            // verify required parameter 'graphElementId' is not null or undefined
            if (graphElementId === null || graphElementId === undefined) {
                throw new RequiredError('graphElementId','Required parameter graphElementId was null or undefined when calling addHeadTerm.');
            }
            const localVarPath = `/queryGraph/head/add/{graphElementId}`
                .replace(`{${"graphElementId"}}`, encodeURIComponent(String(graphElementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This path should be used to build the query graph using the path interaction. As a result there will be added to the query several triple pattern (depending on the length of the path) as a sequence of classes and object properties. Data properties never appear in paths, in order to add them use the simple PUT route.
         * @summary Get the query graph that will be rendered by Sparqling, the query head, the sparql code based on the chosen path.
         * @param {QueryGraph} body 
         * @param {string} path Serialization of Path object.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPathToQueryGraph: async (body: QueryGraph, path: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling addPathToQueryGraph.');
            }
            // verify required parameter 'path' is not null or undefined
            if (path === null || path === undefined) {
                throw new RequiredError('path','Required parameter path was null or undefined when calling addPathToQueryGraph.');
            }
            const localVarPath = `/queryGraph/path`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (path !== undefined) {
                localVarQueryParameter['path'] = path;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This route is used when the user wants to delete a node from the query graph. All the children of this node will be deleted as well as we do not want to create query with completly separated branches. All the variables that are going to be deleted should also be deleted from the head of the query. **WARNING**, if the node has multiple occurrences (due to join operations) every node should be deleted.
         * @summary Delete the GraphElement (and all its children) from the query graph and head.
         * @param {QueryGraph} body 
         * @param {string} graphElementId The GraphElement that should be delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGraphElementId: async (body: QueryGraph, graphElementId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling deleteGraphElementId.');
            }
            // verify required parameter 'graphElementId' is not null or undefined
            if (graphElementId === null || graphElementId === undefined) {
                throw new RequiredError('graphElementId','Required parameter graphElementId was null or undefined when calling deleteGraphElementId.');
            }
            const localVarPath = `/queryGraph/node/delete/{graphElementId}`
                .replace(`{${"graphElementId"}}`, encodeURIComponent(String(graphElementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete the head term from the query graph.
         * @param {QueryGraph} body 
         * @param {string} headTerm The head term that should be delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHeadTerm: async (body: QueryGraph, headTerm: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling deleteHeadTerm.');
            }
            // verify required parameter 'headTerm' is not null or undefined
            if (headTerm === null || headTerm === undefined) {
                throw new RequiredError('headTerm','Required parameter headTerm was null or undefined when calling deleteHeadTerm.');
            }
            const localVarPath = `/queryGraph/head/delete/{headTerm}`
                .replace(`{${"headTerm"}}`, encodeURIComponent(String(headTerm)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Starting from only the clicked class get the query graph that will be rendered by Sparqling, the query head, the sparql code. The sparql query returned will be somthing like `select ?x { ?x a <clickedClassIRI>` }. The variable `?x` should be called according to the entity remainder or label. The variable will be added to the head of the query in order to create a valid SPARQL query.
         * @summary This is the first route to call in order to build the query graph.
         * @param {string} clickedClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueryGraph: async (clickedClassIRI: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clickedClassIRI' is not null or undefined
            if (clickedClassIRI === null || clickedClassIRI === undefined) {
                throw new RequiredError('clickedClassIRI','Required parameter clickedClassIRI was null or undefined when calling getQueryGraph.');
            }
            const localVarPath = `/queryGraph/node`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clickedClassIRI !== undefined) {
                localVarQueryParameter['clickedClassIRI'] = clickedClassIRI;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This route will return the same query graph passed in the body but the SPARQL code with the new filters optionals group by and havings. Note that if the filters are related to optional variables they should be put inside the optional block.
         * @summary Translate the query graph in sparql.
         * @param {QueryGraph} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyFilters: async (body: QueryGraph, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling modifyFilters.');
            }
            const localVarPath = `/queryGraph/translate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This call is used when the user click on a highlighted class and should add a triple pattern of the form like `?x rdf:type <targetClassIRI>`. The server should find `?x` in the SPARQL code as the variable associated to the `sourceClassIRI`.
         * @summary Starting from the current query graph continue to build the query graph through a class.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphClass: async (body: QueryGraph, sourceClassIRI: string, targetClassIRI: string, graphElementId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putQueryGraphClass.');
            }
            // verify required parameter 'sourceClassIRI' is not null or undefined
            if (sourceClassIRI === null || sourceClassIRI === undefined) {
                throw new RequiredError('sourceClassIRI','Required parameter sourceClassIRI was null or undefined when calling putQueryGraphClass.');
            }
            // verify required parameter 'targetClassIRI' is not null or undefined
            if (targetClassIRI === null || targetClassIRI === undefined) {
                throw new RequiredError('targetClassIRI','Required parameter targetClassIRI was null or undefined when calling putQueryGraphClass.');
            }
            // verify required parameter 'graphElementId' is not null or undefined
            if (graphElementId === null || graphElementId === undefined) {
                throw new RequiredError('graphElementId','Required parameter graphElementId was null or undefined when calling putQueryGraphClass.');
            }
            const localVarPath = `/queryGraph/node/class/{graphElementId}`
                .replace(`{${"graphElementId"}}`, encodeURIComponent(String(graphElementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sourceClassIRI !== undefined) {
                localVarQueryParameter['sourceClassIRI'] = sourceClassIRI;
            }

            if (targetClassIRI !== undefined) {
                localVarQueryParameter['targetClassIRI'] = targetClassIRI;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This route is used when the user click a highlighted data property. The triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` should be derived from `selectedClassIRI`. Note that `?y` is fresh new variable that should be added also to the head of the query (we assume data property values are interesting). The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that data property.
         * @summary Starting from the current query graph continue to build the query graph through a data property.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} predicateIRI The IRI of the clicked data property.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphDataProperty: async (body: QueryGraph, sourceClassIRI: string, predicateIRI: string, graphElementId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putQueryGraphDataProperty.');
            }
            // verify required parameter 'sourceClassIRI' is not null or undefined
            if (sourceClassIRI === null || sourceClassIRI === undefined) {
                throw new RequiredError('sourceClassIRI','Required parameter sourceClassIRI was null or undefined when calling putQueryGraphDataProperty.');
            }
            // verify required parameter 'predicateIRI' is not null or undefined
            if (predicateIRI === null || predicateIRI === undefined) {
                throw new RequiredError('predicateIRI','Required parameter predicateIRI was null or undefined when calling putQueryGraphDataProperty.');
            }
            // verify required parameter 'graphElementId' is not null or undefined
            if (graphElementId === null || graphElementId === undefined) {
                throw new RequiredError('graphElementId','Required parameter graphElementId was null or undefined when calling putQueryGraphDataProperty.');
            }
            const localVarPath = `/queryGraph/node/dataProperty/{graphElementId}`
                .replace(`{${"graphElementId"}}`, encodeURIComponent(String(graphElementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sourceClassIRI !== undefined) {
                localVarQueryParameter['sourceClassIRI'] = sourceClassIRI;
            }

            if (predicateIRI !== undefined) {
                localVarQueryParameter['predicateIRI'] = predicateIRI;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Starting from a query graph which has two nodes representing the same class, it returns the query graph in which the two nodes have been joined into a single one. The children of the selected nodes will be grouped in `graphElementId1` and each time we add a children through the previous routes they will be added to this node.
         * @summary Join two GraphNodeElement in one. graph through a data property.
         * @param {QueryGraph} body 
         * @param {string} graphElementId1 The id of the node of the selected class in the query graph.
         * @param {string} graphElementId2 The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphJoin: async (body: QueryGraph, graphElementId1: string, graphElementId2: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putQueryGraphJoin.');
            }
            // verify required parameter 'graphElementId1' is not null or undefined
            if (graphElementId1 === null || graphElementId1 === undefined) {
                throw new RequiredError('graphElementId1','Required parameter graphElementId1 was null or undefined when calling putQueryGraphJoin.');
            }
            // verify required parameter 'graphElementId2' is not null or undefined
            if (graphElementId2 === null || graphElementId2 === undefined) {
                throw new RequiredError('graphElementId2','Required parameter graphElementId2 was null or undefined when calling putQueryGraphJoin.');
            }
            const localVarPath = `/queryGraph/node/join/{graphElementId1}/{graphElementId2}`
                .replace(`{${"graphElementId1"}}`, encodeURIComponent(String(graphElementId1)))
                .replace(`{${"graphElementId2"}}`, encodeURIComponent(String(graphElementId2)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This route is used when the user click a highlighted object property with ornly one `relatedClasses` or, in the case of more than one `relatedClasses` immediatly after choosing one of them. In this case the triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` and `?y` should be derived from the direction indicated by `isPredicateDirect` of the object property with respect to `sourceClassIRI` and `targetClassIRI`. If there is a cyclic object property the user also should specify the direction if order to correctly assign `?x` and `?y`. Either `?x` or `?y` should be a fresh new variable which should be linked to a new triple pattern `?y rdf:type <targetClassIRI>`. The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that class.
         * @summary Starting from the current query graph continue to build the query graph through a object property.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} predicateIRI The IRI of the predicate which links source class and target class
         * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
         * @param {boolean} isPredicateDirect If true sourceClassIRI is the domain of predicateIRI, if false sourceClassIRI is the range of predicateIRI.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphObjectProperty: async (body: QueryGraph, sourceClassIRI: string, predicateIRI: string, targetClassIRI: string, isPredicateDirect: boolean, graphElementId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putQueryGraphObjectProperty.');
            }
            // verify required parameter 'sourceClassIRI' is not null or undefined
            if (sourceClassIRI === null || sourceClassIRI === undefined) {
                throw new RequiredError('sourceClassIRI','Required parameter sourceClassIRI was null or undefined when calling putQueryGraphObjectProperty.');
            }
            // verify required parameter 'predicateIRI' is not null or undefined
            if (predicateIRI === null || predicateIRI === undefined) {
                throw new RequiredError('predicateIRI','Required parameter predicateIRI was null or undefined when calling putQueryGraphObjectProperty.');
            }
            // verify required parameter 'targetClassIRI' is not null or undefined
            if (targetClassIRI === null || targetClassIRI === undefined) {
                throw new RequiredError('targetClassIRI','Required parameter targetClassIRI was null or undefined when calling putQueryGraphObjectProperty.');
            }
            // verify required parameter 'isPredicateDirect' is not null or undefined
            if (isPredicateDirect === null || isPredicateDirect === undefined) {
                throw new RequiredError('isPredicateDirect','Required parameter isPredicateDirect was null or undefined when calling putQueryGraphObjectProperty.');
            }
            // verify required parameter 'graphElementId' is not null or undefined
            if (graphElementId === null || graphElementId === undefined) {
                throw new RequiredError('graphElementId','Required parameter graphElementId was null or undefined when calling putQueryGraphObjectProperty.');
            }
            const localVarPath = `/queryGraph/node/objectProperty/{graphElementId}`
                .replace(`{${"graphElementId"}}`, encodeURIComponent(String(graphElementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sourceClassIRI !== undefined) {
                localVarQueryParameter['sourceClassIRI'] = sourceClassIRI;
            }

            if (predicateIRI !== undefined) {
                localVarQueryParameter['predicateIRI'] = predicateIRI;
            }

            if (targetClassIRI !== undefined) {
                localVarQueryParameter['targetClassIRI'] = targetClassIRI;
            }

            if (isPredicateDirect !== undefined) {
                localVarQueryParameter['isPredicateDirect'] = isPredicateDirect;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QueryGraphApi - functional programming interface
 * @export
 */
export const QueryGraphApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Explicitley add a term to the query head. All the data property variables are added automatically to the head during the query graph construction. This will add to the head only variables associated to classes (`rdf:type` triple pattern) or data properties.
         * @summary Add the head term to the query graph.
         * @param {QueryGraph} body 
         * @param {string} graphElementId The id of the graph node that should be added to the head
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addHeadTerm(body: QueryGraph, graphElementId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).addHeadTerm(body, graphElementId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This path should be used to build the query graph using the path interaction. As a result there will be added to the query several triple pattern (depending on the length of the path) as a sequence of classes and object properties. Data properties never appear in paths, in order to add them use the simple PUT route.
         * @summary Get the query graph that will be rendered by Sparqling, the query head, the sparql code based on the chosen path.
         * @param {QueryGraph} body 
         * @param {string} path Serialization of Path object.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addPathToQueryGraph(body: QueryGraph, path: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).addPathToQueryGraph(body, path, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This route is used when the user wants to delete a node from the query graph. All the children of this node will be deleted as well as we do not want to create query with completly separated branches. All the variables that are going to be deleted should also be deleted from the head of the query. **WARNING**, if the node has multiple occurrences (due to join operations) every node should be deleted.
         * @summary Delete the GraphElement (and all its children) from the query graph and head.
         * @param {QueryGraph} body 
         * @param {string} graphElementId The GraphElement that should be delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteGraphElementId(body: QueryGraph, graphElementId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).deleteGraphElementId(body, graphElementId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete the head term from the query graph.
         * @param {QueryGraph} body 
         * @param {string} headTerm The head term that should be delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteHeadTerm(body: QueryGraph, headTerm: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).deleteHeadTerm(body, headTerm, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Starting from only the clicked class get the query graph that will be rendered by Sparqling, the query head, the sparql code. The sparql query returned will be somthing like `select ?x { ?x a <clickedClassIRI>` }. The variable `?x` should be called according to the entity remainder or label. The variable will be added to the head of the query in order to create a valid SPARQL query.
         * @summary This is the first route to call in order to build the query graph.
         * @param {string} clickedClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQueryGraph(clickedClassIRI: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).getQueryGraph(clickedClassIRI, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This route will return the same query graph passed in the body but the SPARQL code with the new filters optionals group by and havings. Note that if the filters are related to optional variables they should be put inside the optional block.
         * @summary Translate the query graph in sparql.
         * @param {QueryGraph} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyFilters(body: QueryGraph, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).modifyFilters(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This call is used when the user click on a highlighted class and should add a triple pattern of the form like `?x rdf:type <targetClassIRI>`. The server should find `?x` in the SPARQL code as the variable associated to the `sourceClassIRI`.
         * @summary Starting from the current query graph continue to build the query graph through a class.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putQueryGraphClass(body: QueryGraph, sourceClassIRI: string, targetClassIRI: string, graphElementId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).putQueryGraphClass(body, sourceClassIRI, targetClassIRI, graphElementId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This route is used when the user click a highlighted data property. The triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` should be derived from `selectedClassIRI`. Note that `?y` is fresh new variable that should be added also to the head of the query (we assume data property values are interesting). The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that data property.
         * @summary Starting from the current query graph continue to build the query graph through a data property.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} predicateIRI The IRI of the clicked data property.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putQueryGraphDataProperty(body: QueryGraph, sourceClassIRI: string, predicateIRI: string, graphElementId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).putQueryGraphDataProperty(body, sourceClassIRI, predicateIRI, graphElementId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Starting from a query graph which has two nodes representing the same class, it returns the query graph in which the two nodes have been joined into a single one. The children of the selected nodes will be grouped in `graphElementId1` and each time we add a children through the previous routes they will be added to this node.
         * @summary Join two GraphNodeElement in one. graph through a data property.
         * @param {QueryGraph} body 
         * @param {string} graphElementId1 The id of the node of the selected class in the query graph.
         * @param {string} graphElementId2 The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putQueryGraphJoin(body: QueryGraph, graphElementId1: string, graphElementId2: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).putQueryGraphJoin(body, graphElementId1, graphElementId2, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This route is used when the user click a highlighted object property with ornly one `relatedClasses` or, in the case of more than one `relatedClasses` immediatly after choosing one of them. In this case the triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` and `?y` should be derived from the direction indicated by `isPredicateDirect` of the object property with respect to `sourceClassIRI` and `targetClassIRI`. If there is a cyclic object property the user also should specify the direction if order to correctly assign `?x` and `?y`. Either `?x` or `?y` should be a fresh new variable which should be linked to a new triple pattern `?y rdf:type <targetClassIRI>`. The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that class.
         * @summary Starting from the current query graph continue to build the query graph through a object property.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} predicateIRI The IRI of the predicate which links source class and target class
         * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
         * @param {boolean} isPredicateDirect If true sourceClassIRI is the domain of predicateIRI, if false sourceClassIRI is the range of predicateIRI.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putQueryGraphObjectProperty(body: QueryGraph, sourceClassIRI: string, predicateIRI: string, targetClassIRI: string, isPredicateDirect: boolean, graphElementId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryGraph>> {
            const localVarAxiosArgs = await QueryGraphApiAxiosParamCreator(configuration).putQueryGraphObjectProperty(body, sourceClassIRI, predicateIRI, targetClassIRI, isPredicateDirect, graphElementId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * QueryGraphApi - factory interface
 * @export
 */
export const QueryGraphApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Explicitley add a term to the query head. All the data property variables are added automatically to the head during the query graph construction. This will add to the head only variables associated to classes (`rdf:type` triple pattern) or data properties.
         * @summary Add the head term to the query graph.
         * @param {QueryGraph} body 
         * @param {string} graphElementId The id of the graph node that should be added to the head
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addHeadTerm(body: QueryGraph, graphElementId: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).addHeadTerm(body, graphElementId, options).then((request) => request(axios, basePath));
        },
        /**
         * This path should be used to build the query graph using the path interaction. As a result there will be added to the query several triple pattern (depending on the length of the path) as a sequence of classes and object properties. Data properties never appear in paths, in order to add them use the simple PUT route.
         * @summary Get the query graph that will be rendered by Sparqling, the query head, the sparql code based on the chosen path.
         * @param {QueryGraph} body 
         * @param {string} path Serialization of Path object.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPathToQueryGraph(body: QueryGraph, path: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).addPathToQueryGraph(body, path, options).then((request) => request(axios, basePath));
        },
        /**
         * This route is used when the user wants to delete a node from the query graph. All the children of this node will be deleted as well as we do not want to create query with completly separated branches. All the variables that are going to be deleted should also be deleted from the head of the query. **WARNING**, if the node has multiple occurrences (due to join operations) every node should be deleted.
         * @summary Delete the GraphElement (and all its children) from the query graph and head.
         * @param {QueryGraph} body 
         * @param {string} graphElementId The GraphElement that should be delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGraphElementId(body: QueryGraph, graphElementId: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).deleteGraphElementId(body, graphElementId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete the head term from the query graph.
         * @param {QueryGraph} body 
         * @param {string} headTerm The head term that should be delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHeadTerm(body: QueryGraph, headTerm: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).deleteHeadTerm(body, headTerm, options).then((request) => request(axios, basePath));
        },
        /**
         * Starting from only the clicked class get the query graph that will be rendered by Sparqling, the query head, the sparql code. The sparql query returned will be somthing like `select ?x { ?x a <clickedClassIRI>` }. The variable `?x` should be called according to the entity remainder or label. The variable will be added to the head of the query in order to create a valid SPARQL query.
         * @summary This is the first route to call in order to build the query graph.
         * @param {string} clickedClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueryGraph(clickedClassIRI: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).getQueryGraph(clickedClassIRI, options).then((request) => request(axios, basePath));
        },
        /**
         * This route will return the same query graph passed in the body but the SPARQL code with the new filters optionals group by and havings. Note that if the filters are related to optional variables they should be put inside the optional block.
         * @summary Translate the query graph in sparql.
         * @param {QueryGraph} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyFilters(body: QueryGraph, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).modifyFilters(body, options).then((request) => request(axios, basePath));
        },
        /**
         * This call is used when the user click on a highlighted class and should add a triple pattern of the form like `?x rdf:type <targetClassIRI>`. The server should find `?x` in the SPARQL code as the variable associated to the `sourceClassIRI`.
         * @summary Starting from the current query graph continue to build the query graph through a class.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphClass(body: QueryGraph, sourceClassIRI: string, targetClassIRI: string, graphElementId: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).putQueryGraphClass(body, sourceClassIRI, targetClassIRI, graphElementId, options).then((request) => request(axios, basePath));
        },
        /**
         * This route is used when the user click a highlighted data property. The triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` should be derived from `selectedClassIRI`. Note that `?y` is fresh new variable that should be added also to the head of the query (we assume data property values are interesting). The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that data property.
         * @summary Starting from the current query graph continue to build the query graph through a data property.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} predicateIRI The IRI of the clicked data property.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphDataProperty(body: QueryGraph, sourceClassIRI: string, predicateIRI: string, graphElementId: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).putQueryGraphDataProperty(body, sourceClassIRI, predicateIRI, graphElementId, options).then((request) => request(axios, basePath));
        },
        /**
         * Starting from a query graph which has two nodes representing the same class, it returns the query graph in which the two nodes have been joined into a single one. The children of the selected nodes will be grouped in `graphElementId1` and each time we add a children through the previous routes they will be added to this node.
         * @summary Join two GraphNodeElement in one. graph through a data property.
         * @param {QueryGraph} body 
         * @param {string} graphElementId1 The id of the node of the selected class in the query graph.
         * @param {string} graphElementId2 The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphJoin(body: QueryGraph, graphElementId1: string, graphElementId2: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).putQueryGraphJoin(body, graphElementId1, graphElementId2, options).then((request) => request(axios, basePath));
        },
        /**
         * This route is used when the user click a highlighted object property with ornly one `relatedClasses` or, in the case of more than one `relatedClasses` immediatly after choosing one of them. In this case the triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` and `?y` should be derived from the direction indicated by `isPredicateDirect` of the object property with respect to `sourceClassIRI` and `targetClassIRI`. If there is a cyclic object property the user also should specify the direction if order to correctly assign `?x` and `?y`. Either `?x` or `?y` should be a fresh new variable which should be linked to a new triple pattern `?y rdf:type <targetClassIRI>`. The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that class.
         * @summary Starting from the current query graph continue to build the query graph through a object property.
         * @param {QueryGraph} body 
         * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
         * @param {string} predicateIRI The IRI of the predicate which links source class and target class
         * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
         * @param {boolean} isPredicateDirect If true sourceClassIRI is the domain of predicateIRI, if false sourceClassIRI is the range of predicateIRI.
         * @param {string} graphElementId The id of the node of the selected class in the query graph.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putQueryGraphObjectProperty(body: QueryGraph, sourceClassIRI: string, predicateIRI: string, targetClassIRI: string, isPredicateDirect: boolean, graphElementId: string, options?: any): AxiosPromise<QueryGraph> {
            return QueryGraphApiFp(configuration).putQueryGraphObjectProperty(body, sourceClassIRI, predicateIRI, targetClassIRI, isPredicateDirect, graphElementId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QueryGraphApi - object-oriented interface
 * @export
 * @class QueryGraphApi
 * @extends {BaseAPI}
 */
export class QueryGraphApi extends BaseAPI {
    /**
     * Explicitley add a term to the query head. All the data property variables are added automatically to the head during the query graph construction. This will add to the head only variables associated to classes (`rdf:type` triple pattern) or data properties.
     * @summary Add the head term to the query graph.
     * @param {QueryGraph} body 
     * @param {string} graphElementId The id of the graph node that should be added to the head
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public addHeadTerm(body: QueryGraph, graphElementId: string, options?: any) {
        return QueryGraphApiFp(this.configuration).addHeadTerm(body, graphElementId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This path should be used to build the query graph using the path interaction. As a result there will be added to the query several triple pattern (depending on the length of the path) as a sequence of classes and object properties. Data properties never appear in paths, in order to add them use the simple PUT route.
     * @summary Get the query graph that will be rendered by Sparqling, the query head, the sparql code based on the chosen path.
     * @param {QueryGraph} body 
     * @param {string} path Serialization of Path object.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public addPathToQueryGraph(body: QueryGraph, path: string, options?: any) {
        return QueryGraphApiFp(this.configuration).addPathToQueryGraph(body, path, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This route is used when the user wants to delete a node from the query graph. All the children of this node will be deleted as well as we do not want to create query with completly separated branches. All the variables that are going to be deleted should also be deleted from the head of the query. **WARNING**, if the node has multiple occurrences (due to join operations) every node should be deleted.
     * @summary Delete the GraphElement (and all its children) from the query graph and head.
     * @param {QueryGraph} body 
     * @param {string} graphElementId The GraphElement that should be delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public deleteGraphElementId(body: QueryGraph, graphElementId: string, options?: any) {
        return QueryGraphApiFp(this.configuration).deleteGraphElementId(body, graphElementId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete the head term from the query graph.
     * @param {QueryGraph} body 
     * @param {string} headTerm The head term that should be delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public deleteHeadTerm(body: QueryGraph, headTerm: string, options?: any) {
        return QueryGraphApiFp(this.configuration).deleteHeadTerm(body, headTerm, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Starting from only the clicked class get the query graph that will be rendered by Sparqling, the query head, the sparql code. The sparql query returned will be somthing like `select ?x { ?x a <clickedClassIRI>` }. The variable `?x` should be called according to the entity remainder or label. The variable will be added to the head of the query in order to create a valid SPARQL query.
     * @summary This is the first route to call in order to build the query graph.
     * @param {string} clickedClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public getQueryGraph(clickedClassIRI: string, options?: any) {
        return QueryGraphApiFp(this.configuration).getQueryGraph(clickedClassIRI, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This route will return the same query graph passed in the body but the SPARQL code with the new filters optionals group by and havings. Note that if the filters are related to optional variables they should be put inside the optional block.
     * @summary Translate the query graph in sparql.
     * @param {QueryGraph} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public modifyFilters(body: QueryGraph, options?: any) {
        return QueryGraphApiFp(this.configuration).modifyFilters(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This call is used when the user click on a highlighted class and should add a triple pattern of the form like `?x rdf:type <targetClassIRI>`. The server should find `?x` in the SPARQL code as the variable associated to the `sourceClassIRI`.
     * @summary Starting from the current query graph continue to build the query graph through a class.
     * @param {QueryGraph} body 
     * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
     * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
     * @param {string} graphElementId The id of the node of the selected class in the query graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public putQueryGraphClass(body: QueryGraph, sourceClassIRI: string, targetClassIRI: string, graphElementId: string, options?: any) {
        return QueryGraphApiFp(this.configuration).putQueryGraphClass(body, sourceClassIRI, targetClassIRI, graphElementId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This route is used when the user click a highlighted data property. The triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` should be derived from `selectedClassIRI`. Note that `?y` is fresh new variable that should be added also to the head of the query (we assume data property values are interesting). The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that data property.
     * @summary Starting from the current query graph continue to build the query graph through a data property.
     * @param {QueryGraph} body 
     * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
     * @param {string} predicateIRI The IRI of the clicked data property.
     * @param {string} graphElementId The id of the node of the selected class in the query graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public putQueryGraphDataProperty(body: QueryGraph, sourceClassIRI: string, predicateIRI: string, graphElementId: string, options?: any) {
        return QueryGraphApiFp(this.configuration).putQueryGraphDataProperty(body, sourceClassIRI, predicateIRI, graphElementId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Starting from a query graph which has two nodes representing the same class, it returns the query graph in which the two nodes have been joined into a single one. The children of the selected nodes will be grouped in `graphElementId1` and each time we add a children through the previous routes they will be added to this node.
     * @summary Join two GraphNodeElement in one. graph through a data property.
     * @param {QueryGraph} body 
     * @param {string} graphElementId1 The id of the node of the selected class in the query graph.
     * @param {string} graphElementId2 The id of the node of the selected class in the query graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public putQueryGraphJoin(body: QueryGraph, graphElementId1: string, graphElementId2: string, options?: any) {
        return QueryGraphApiFp(this.configuration).putQueryGraphJoin(body, graphElementId1, graphElementId2, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This route is used when the user click a highlighted object property with ornly one `relatedClasses` or, in the case of more than one `relatedClasses` immediatly after choosing one of them. In this case the triple pattern to add is something like `?x <predicateIRI> ?y` where `?x` and `?y` should be derived from the direction indicated by `isPredicateDirect` of the object property with respect to `sourceClassIRI` and `targetClassIRI`. If there is a cyclic object property the user also should specify the direction if order to correctly assign `?x` and `?y`. Either `?x` or `?y` should be a fresh new variable which should be linked to a new triple pattern `?y rdf:type <targetClassIRI>`. The variable `?y` should be called according to the entity remainder or label and should add a counter if there is an already defined variable for that class.
     * @summary Starting from the current query graph continue to build the query graph through a object property.
     * @param {QueryGraph} body 
     * @param {string} sourceClassIRI The IRI of the last selected class. It could be selected from the ontology graph or from the query graph.
     * @param {string} predicateIRI The IRI of the predicate which links source class and target class
     * @param {string} targetClassIRI The IRI of the entity clicked on the GRAPHOLscape ontology graph.
     * @param {boolean} isPredicateDirect If true sourceClassIRI is the domain of predicateIRI, if false sourceClassIRI is the range of predicateIRI.
     * @param {string} graphElementId The id of the node of the selected class in the query graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryGraphApi
     */
    public putQueryGraphObjectProperty(body: QueryGraph, sourceClassIRI: string, predicateIRI: string, targetClassIRI: string, isPredicateDirect: boolean, graphElementId: string, options?: any) {
        return QueryGraphApiFp(this.configuration).putQueryGraphObjectProperty(body, sourceClassIRI, predicateIRI, targetClassIRI, isPredicateDirect, graphElementId, options).then((request) => request(this.axios, this.basePath));
    }
}
